import type { Locale } from "@/lib/locale";

export const articleDetailCopy = {
  en: { metaFallback: "Article | Amjad Osman", glance: "Article at a glance", category: "Category", published: "Published", reading: "Reading time", readingUnit: "min", relatedTools: "Related tools", readNext: "Read next", summaryFallback: "This article summary is available now. Reach out if you want the full implementation notes.", bookCall: "Book a Call", viewPricing: "View pricing", toolLabels: { dashboard: "Dashboard Builder", process: "Process Mapper" } },
  ar: { metaFallback: "المقال | أمجد عثمان", glance: "لمحة عن المقال", category: "التصنيف", published: "نُشر", reading: "القراءة", readingUnit: "دقائق", relatedTools: "أدوات مرتبطة", readNext: "اقرأ أيضاً", summaryFallback: "هذا الملخص متاح حالياً. تواصل معنا إذا كنت تريد ملاحظات التنفيذ الكاملة.", bookCall: "احجز مكالمة", viewPricing: "عرض الأسعار", toolLabels: { dashboard: "منشئ لوحة البيانات", process: "خريطة العمليات" } },
  de: { metaFallback: "Artikel | Amjad Osman", glance: "Zum Artikel", category: "Kategorie", published: "Veröffentlicht", reading: "Lesezeit", readingUnit: "Minuten", relatedTools: "Verwandte Tools", readNext: "Weiterlesen", summaryFallback: "Diese Artikelzusammenfassung ist verfügbar. Kontaktieren Sie mich für die vollständigen Umsetzungshinweise.", bookCall: "Gespräch buchen", viewPricing: "Preise ansehen", toolLabels: { dashboard: "Dashboard-Spezifikation", process: "Prozesskarte" } },
  fr: { metaFallback: "Article | Amjad Osman", glance: "À propos de l'article", category: "Catégorie", published: "Publié", reading: "Lecture", readingUnit: "min", relatedTools: "Outils associés", readNext: "À lire aussi", summaryFallback: "Le résumé de cet article est disponible. Contactez-moi pour obtenir les notes d'exécution complètes.", bookCall: "Réserver un appel", viewPricing: "Voir les tarifs", toolLabels: { dashboard: "Spécification dashboard", process: "Cartographie processus" } },
  bg: { metaFallback: "Статия | Amjad Osman", glance: "За статията", category: "Категория", published: "Публикувано", reading: "Четене", readingUnit: "мин", relatedTools: "Свързани инструменти", readNext: "Още", summaryFallback: "Резюмето на тази статия е налично. Свържете се с мен за пълните бележки по изпълнението.", bookCall: "Запишете разговор", viewPricing: "Вижте цените", toolLabels: { dashboard: "Спецификация на табло", process: "Карта на процеса" } },
} satisfies Record<Locale, Record<string, unknown>>;

export const workDetailCopy = {
  en: { metaFallback: "Case Study | Amjad Osman", glance: "Project at a glance", partner: "Partner", year: "Year", sector: "Sector", role: "Role", outcome: "Outcome", gallery: "Project gallery", related: "Related cases from this client", ctaHeadline: "Scope similar work.", ctaDescription: "We'll shape the first engagement around your bottleneck, timeline, and price.", bookCall: "Book a Call", viewPricing: "View pricing" },
  ar: { metaFallback: "دراسة الحالة | أمجد عثمان", glance: "لمحة عن المشروع", partner: "الشريك", year: "السنة", sector: "القطاع", role: "الدور", outcome: "النتيجة", gallery: "صور المشروع", related: "دراسات مرتبطة من نفس العميل", ctaHeadline: "حدد عملاً مشابهاً.", ctaDescription: "سنصمم أول مرحلة حول اختناقك الحالي والجدول الزمني والسعر.", bookCall: "احجز مكالمة", viewPricing: "عرض الأسعار" },
  de: { metaFallback: "Fallstudie | Amjad Osman", glance: "Projekt auf einen Blick", partner: "Partner", year: "Jahr", sector: "Branche", role: "Rolle", outcome: "Ergebnis", gallery: "Projektgalerie", related: "Weitere Fälle dieses Kunden", ctaHeadline: "Ähnliche Arbeit klar abgrenzen.", ctaDescription: "Wir richten den ersten Auftrag an Ihrem Engpass, Zeitplan und Budget aus.", bookCall: "Gespräch buchen", viewPricing: "Preise ansehen" },
  fr: { metaFallback: "Étude de cas | Amjad Osman", glance: "Le projet en bref", partner: "Partenaire", year: "Année", sector: "Secteur", role: "Rôle", outcome: "Résultat", gallery: "Galerie du projet", related: "Autres cas pour ce client", ctaHeadline: "Cadrons un travail similaire.", ctaDescription: "Nous construirons le premier engagement autour de votre blocage, de votre calendrier et de votre budget.", bookCall: "Réserver un appel", viewPricing: "Voir les tarifs" },
  bg: { metaFallback: "Казус | Amjad Osman", glance: "Проектът накратко", partner: "Партньор", year: "Година", sector: "Сектор", role: "Роля", outcome: "Резултат", gallery: "Галерия на проекта", related: "Свързани казуси за този клиент", ctaHeadline: "Нека уточним сходна работа.", ctaDescription: "Ще оформим първия ангажимент около вашето затруднение, срок и бюджет.", bookCall: "Запишете разговор", viewPricing: "Вижте цените" },
} satisfies Record<Locale, Record<string, string>>;
