import type { Locale } from "@/lib/locale";

export const uiCopy = {
  en: {
    bookCall: "Book a Call", bookCallLower: "Book a call", startService: "Start service", singleService: "Single service", starterPackage: "Starter package", startPackage: "Start this package", talkItThrough: "Talk it through", retainer: "Retainer", startRetainer: "Start retainer", fixedScopePackages: "Fixed-scope packages", singleServiceMenu: "Single-service menu", ongoingSupport: "Ongoing support", learnMore: "Learn more", projectPreview: "Project Preview", explore: "Explore", configuration: "Configuration", governancePreset: "Governance preset:", simple: "Simple", strict: "Strict", role: "Role", stage: "Stage", deliveryProgress: "Delivery progress", of: "of", pain: "Pain:", payoff: "Payoff:", sending: "Sending...", emailAddress: "Email address", enterEmail: "Enter your email", invalidEmail: "Please enter a valid email address", downloadError: "The download could not be prepared.", notFound: "Oops! Page not found", returnHome: "Return to Home", setup: "Configuration", actionCreate: "Create", actionApprove: "Approve", actionExport: "Export", actionDelete: "Delete", roleAdmin: "Admin", roleManager: "Manager", roleStaff: "Staff", roleViewer: "Viewer"
  },
  ar: {
    bookCall: "احجز مكالمة", bookCallLower: "احجز مكالمة", startService: "ابدأ الخدمة", singleService: "خدمة منفردة", starterPackage: "باقة بداية", startPackage: "ابدأ هذه الباقة", talkItThrough: "ناقشها معنا", retainer: "دعم مستمر", startRetainer: "ابدأ الدعم", fixedScopePackages: "باقات بنطاق ثابت", singleServiceMenu: "خدمات منفردة", ongoingSupport: "دعم مستمر", learnMore: "اعرف المزيد", projectPreview: "معاينة المشروع", explore: "استكشف", configuration: "الإعداد", governancePreset: "إعداد الحوكمة:", simple: "مبسّط", strict: "صارم", role: "الدور", stage: "المرحلة", deliveryProgress: "تقدم التسليم", of: "من", pain: "المشكلة:", payoff: "النتيجة:", sending: "جارٍ الإرسال...", emailAddress: "البريد الإلكتروني", enterEmail: "أدخل بريدك الإلكتروني", invalidEmail: "يرجى إدخال بريد إلكتروني صالح", downloadError: "تعذر تجهيز التنزيل.", notFound: "عذراً، الصفحة غير موجودة", returnHome: "العودة إلى الرئيسية", setup: "الإعداد", actionCreate: "إنشاء", actionApprove: "اعتماد", actionExport: "تصدير", actionDelete: "حذف", roleAdmin: "مشرف", roleManager: "مدير", roleStaff: "موظف", roleViewer: "مشاهد"
  },
  de: {
    bookCall: "Gespräch buchen", bookCallLower: "Gespräch buchen", startService: "Service starten", singleService: "Einzelservice", starterPackage: "Startpaket", startPackage: "Paket starten", talkItThrough: "Besprechen", retainer: "Laufende Unterstützung", startRetainer: "Unterstützung starten", fixedScopePackages: "Pakete mit festem Umfang", singleServiceMenu: "Einzelservices", ongoingSupport: "Laufende Unterstützung", learnMore: "Mehr erfahren", projectPreview: "Projektvorschau", explore: "Entdecken", configuration: "Konfiguration", governancePreset: "Governance-Voreinstellung:", simple: "Einfach", strict: "Streng", role: "Rolle", stage: "Phase", deliveryProgress: "Lieferfortschritt", of: "von", pain: "Problem:", payoff: "Nutzen:", sending: "Wird gesendet...", emailAddress: "E-Mail-Adresse", enterEmail: "E-Mail-Adresse eingeben", invalidEmail: "Bitte eine gültige E-Mail-Adresse eingeben", downloadError: "Der Download konnte nicht vorbereitet werden.", notFound: "Die Seite wurde nicht gefunden", returnHome: "Zur Startseite", setup: "Konfiguration", actionCreate: "Erstellen", actionApprove: "Freigeben", actionExport: "Exportieren", actionDelete: "Löschen", roleAdmin: "Admin", roleManager: "Manager", roleStaff: "Mitarbeiter", roleViewer: "Leser"
  },
  fr: {
    bookCall: "Réserver un appel", bookCallLower: "Réserver un appel", startService: "Démarrer le service", singleService: "Service individuel", starterPackage: "Package de départ", startPackage: "Démarrer ce package", talkItThrough: "En parler", retainer: "Accompagnement continu", startRetainer: "Démarrer l'accompagnement", fixedScopePackages: "Packages à périmètre fixe", singleServiceMenu: "Services individuels", ongoingSupport: "Accompagnement continu", learnMore: "En savoir plus", projectPreview: "Aperçu du projet", explore: "Explorer", configuration: "Configuration", governancePreset: "Préréglage de gouvernance :", simple: "Simple", strict: "Strict", role: "Rôle", stage: "Étape", deliveryProgress: "Progression de la livraison", of: "sur", pain: "Problème :", payoff: "Bénéfice :", sending: "Envoi...", emailAddress: "Adresse e-mail", enterEmail: "Saisissez votre e-mail", invalidEmail: "Saisissez une adresse e-mail valide", downloadError: "Le téléchargement n'a pas pu être préparé.", notFound: "Page introuvable", returnHome: "Retour à l'accueil", setup: "Configuration", actionCreate: "Créer", actionApprove: "Approuver", actionExport: "Exporter", actionDelete: "Supprimer", roleAdmin: "Admin", roleManager: "Manager", roleStaff: "Équipe", roleViewer: "Lecteur"
  },
  bg: {
    bookCall: "Запишете разговор", bookCallLower: "Запишете разговор", startService: "Стартирайте услугата", singleService: "Единична услуга", starterPackage: "Стартов пакет", startPackage: "Стартирайте пакета", talkItThrough: "Обсъдете го", retainer: "Постоянна поддръжка", startRetainer: "Стартирайте поддръжката", fixedScopePackages: "Пакети с ясен обхват", singleServiceMenu: "Единични услуги", ongoingSupport: "Постоянна поддръжка", learnMore: "Научете повече", projectPreview: "Преглед на проекта", explore: "Разгледайте", configuration: "Конфигурация", governancePreset: "Настройка за управление:", simple: "Опростена", strict: "Строга", role: "Роля", stage: "Етап", deliveryProgress: "Напредък на доставката", of: "от", pain: "Проблем:", payoff: "Полза:", sending: "Изпращане...", emailAddress: "Имейл адрес", enterEmail: "Въведете имейла си", invalidEmail: "Въведете валиден имейл адрес", downloadError: "Изтеглянето не можа да бъде подготвено.", notFound: "Страницата не е намерена", returnHome: "Към началната страница", setup: "Конфигурация", actionCreate: "Създаване", actionApprove: "Одобряване", actionExport: "Експортиране", actionDelete: "Изтриване", roleAdmin: "Администратор", roleManager: "Мениджър", roleStaff: "Служител", roleViewer: "Наблюдател"
  },
} satisfies Record<Locale, Record<string, string>>;

export const getUiCopy = (locale: Locale) => uiCopy[locale] ?? uiCopy.en;
